### ISSUE TITLE
Error:  No such container: market_web

### ISSUE THREAD

**Issue by anujnayyar1** [adyassine/cocorico-docker#1]
Hi Adyassine, 

Firstly thank you for the docker. I am having trouble installing the composer dependancies and am getting the error:

$ docker exec -it market_web composer install
Error response from daemon: No such container: market_web

Can you point me in the right direction?

Regards,

Anuj

**Comment by adyassine** [comment]
Hi, 
you shoud get the right container name 
$ docker ps
$ docker exec -it [container name]

**Comment by anujnayyar1** [comment]
Hi adyassine,

Thanks for your reply. Im still having some problems at this stage:

docker exec -it cocorico_market_web_1 composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer could not find a composer.json file in /var/www/market
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

any help would again be appreciated 

Thanks

Anuj
